[versions]
agp = "8.13.1"
bom = "3.2.2"
coilCompose = "3.3.0"
coilNetworkOkhttp = "3.3.0"
composeMarkdown = "0.5.7"
credentials = "1.5.0"
credentialsPlayServicesAuth = "1.5.0"
firebaseBom = "34.2.0"
googleid = "1.1.1"
hiltAndroidCompiler = "2.57"
hiltAndroid = "2.57.1"
hiltNavigationCompose = "1.2.0"
kotlin = "2.2.10"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
ktorClientAndroid = "3.2.3"
ktorClientOkhttp = "3.2.3"
lifecycleRuntimeKtx = "2.9.3"
activityCompose = "1.10.1"
composeBom = "2024.09.00"
lifecycleViewmodelCompose = "2.9.3"
navigationCompose = "2.9.3"
serialization = "2.2.10"
hilt = "2.57.1"
ksp = "2.2.10-2.0.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentialsPlayServicesAuth" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
auth-kt = { module = "io.github.jan-tennert.supabase:auth-kt" }
bom = { module = "io.github.jan-tennert.supabase:bom", version.ref = "bom" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilNetworkOkhttp" }
compose-markdown = { module = "com.github.jeziellago:compose-markdown", version.ref = "composeMarkdown" }
firebase-ai = { module = "com.google.firebase:firebase-ai" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompiler" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktorClientOkhttp" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktorClientAndroid" }
realtime-kt = { module = "io.github.jan-tennert.supabase:realtime-kt" }
postgrest-kt = { module = "io.github.jan-tennert.supabase:postgrest-kt" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
